"""add audit fields to technicians

Revision ID: b758057e39ce
Revises: f006d0a01f12
Create Date: 2025-11-05 13:31:38.645395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b758057e39ce'
down_revision: Union[str, Sequence[str], None] = 'f006d0a01f12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('technicians', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.add_column('technicians', sa.Column('updated_by_user_id', sa.Integer(), nullable=True))
    op.add_column('technicians', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('technicians', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_technicians_created_by_user_id'), 'technicians', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_technicians_updated_by_user_id'), 'technicians', ['updated_by_user_id'], unique=False)
    op.create_foreign_key(None, 'technicians', 'users', ['updated_by_user_id'], ['id'])
    op.create_foreign_key(None, 'technicians', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'technicians', type_='foreignkey')
    op.drop_constraint(None, 'technicians', type_='foreignkey')
    op.drop_index(op.f('ix_technicians_updated_by_user_id'), table_name='technicians')
    op.drop_index(op.f('ix_technicians_created_by_user_id'), table_name='technicians')
    op.alter_column('technicians', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('technicians', 'updated_at')
    op.drop_column('technicians', 'updated_by_user_id')
    op.drop_column('technicians', 'created_by_user_id')
    # ### end Alembic commands ###
